app/site/__init__.py
from flask import Blueprint

bp = Blueprint('site', __name__)

from app.site import routes

app/site/routes.py
import os
import config
from uuid import uuid4
from app.site import bp
import cloudinary.uploader
from app.extensions import db
from flask_mail import Message
from app.extensions import mail
from app.models.art import Image
from app.site.dall_e import AIArtGenerator
from app.models.subscription import Account
from flask_login import login_required, current_user
from flask import render_template, redirect, url_for, flash, request

response = {"data": []}

ACCOUNT_MANAGEMENT = {
    "free_account": {
        "tier": "Free",
        "max_count": 5,
        "max_images": 1,
        "quality": "256x256"
    },
    "basic_account": {
        "tier": "Basic",
        "max_count": 10,
        "max_images": 2,
        "quality": "512x512"
    },
    "standard_account": {
        "tier": "Standard",
        "max_count": 25,
        "max_images": 3,
        "quality": "512x512"
    },
    "pro_account": {
        "tier": "Pro",
        "max_count": 40,
        "max_images": 4,
        "quality": "1024x1024"
    }
}

@bp.route('/', methods=['GET'])
def home():

    user_account = Account.query.filter_by(user_id=current_user.id)\
                    .first() if current_user.is_authenticated else None

    return render_template(
        'site/home.html',
        this_user=current_user,
        this_account = user_account,
    )

@bp.route('/gallery/', methods=['GET'])
def gallery():

    user_account = Account.query.filter_by(user_id=current_user.id)\
                    .first() if current_user.is_authenticated else None
    
    all_images = Image.query.all()

    return render_template(
        'site/gallery.html',
        this_user=current_user,
        this_account=user_account,
        my_gallery=all_images,
    )

@bp.route('/contacts/', methods=['GET', 'POST'])
def contacts():

    user_account = Account.query.filter_by(user_id=current_user.id)\
                    .first() if current_user.is_authenticated else None
    
    if request.method == 'POST':

        subject = request.form.get('subject')
        sender_email = request.form.get('sender_email')
        message = request.form.get('message')

        mail_body = f"{message} \n\nSent by: {sender_email}"

        msg = Message(
            subject=subject,
            sender=os.environ.get('GMAIL_USERNAME'),
            recipients=[os.environ.get('GMAIL_USERNAME')],
            body=mail_body
        )

        try:

            mail.send(msg)

        except Exception as e:

            flash(f"Error: {str(e)}", "error")
            return None
        
        else:

            flash("Message sent successfully", "message")
            
        return redirect(url_for('site.contacts'))

    return render_template(
        'site/contacts.html',
        this_user=current_user,
        this_account=user_account,
    )

@bp.route('/pricing/', methods=['GET'])
def pricing():

    user_account = Account.query.filter_by(user_id=current_user.id)\
                    .first() if current_user.is_authenticated else None

    return render_template(
        'site/pricing.html',
        this_user=current_user,
        this_account=user_account,
    )

@bp.route('/app/generate_art/', methods=['GET', 'POST'])
@login_required
def generate_art():

    user_account = Account.query.filter_by(user_id=current_user.id).first()
    current_count = int(user_account.generation_count)

    if user_account.subscription == ACCOUNT_MANAGEMENT['free_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['free_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['free_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['free_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['basic_account']['tier']:
        
        max_count = ACCOUNT_MANAGEMENT['basic_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['basic_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['basic_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['standard_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['standard_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['standard_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['standard_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['pro_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['pro_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['pro_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['pro_account']['quality']

    if request.method == 'POST':

        if current_count < max_count:

            style = request.form.get('style')
            text_prompt = request.form.get('text_prompt')

            prompt = text_prompt if style == 'Custom' else f"style: {style}. Description: {text_prompt}"

            image_object = AIArtGenerator(
                prompt=prompt,
                n=max_images,
                size=quality
            )

            response.update({"data": image_object.generate_art()})

            user_account.generation_count += 1

            try:

                db.session.commit()

            except Exception as e:

                flash(f"Error: {str(e)}", "error")
                return None

        else:

            flash("you have reached the limit of your current subscription.", "error")

        return redirect(url_for('site.generate_art'))

    return render_template(
        'site/app/generate_art.html',
        this_user=current_user,
        this_account=user_account,
        max_count=max_count,
        generated_response=response['data']
    )

@bp.route('/app/photo_to_art/', methods=['GET', 'POST'])
@login_required
def photo_to_art():

    user_account = Account.query.filter_by(user_id=current_user.id).first()
    current_count = int(user_account.generation_count)

    if user_account.subscription == ACCOUNT_MANAGEMENT['free_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['free_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['free_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['free_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['basic_account']['tier']:
        
        max_count = ACCOUNT_MANAGEMENT['basic_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['basic_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['basic_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['standard_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['standard_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['standard_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['standard_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['pro_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['pro_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['pro_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['pro_account']['quality']

    if request.method == 'POST':
            
        if current_count < max_count:

            style = request.form.get('style')
            text_prompt = request.form.get('text_prompt')
            image = request.files['image'].stream.read()

            prompt = text_prompt if style == 'Custom' else f"style: {style}. Description: {text_prompt}"

            image_object = AIArtGenerator(
                prompt=prompt,
                n=max_images,
                size=quality
            )

            response.update({"data": image_object.photo_to_art(image=image)})

            user_account.generation_count += 1

            try:

                db.session.commit()

            except Exception as e:

                flash(f"Error: {str(e)}", "error")
                return None

        else:

            flash("you have reached the limit of your current subscription.", "error")

        return redirect(url_for('site.photo_to_art'))

    return render_template(
        'site/app/photo_to_art.html',
        this_user=current_user,
        this_account=user_account,
        max_count=max_count,
        generated_response=response['data']
    )

@bp.route('/app/image_variation/', methods=['GET', 'POST'])
@login_required
def image_variation():

    user_account = Account.query.filter_by(user_id=current_user.id).first()
    current_count = int(user_account.generation_count)

    if user_account.subscription == ACCOUNT_MANAGEMENT['free_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['free_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['free_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['free_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['basic_account']['tier']:
        
        max_count = ACCOUNT_MANAGEMENT['basic_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['basic_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['basic_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['standard_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['standard_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['standard_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['standard_account']['quality']

    elif user_account.subscription == ACCOUNT_MANAGEMENT['pro_account']['tier']:

        max_count = ACCOUNT_MANAGEMENT['pro_account']['max_count']
        max_images = ACCOUNT_MANAGEMENT['pro_account']['max_images']
        quality = ACCOUNT_MANAGEMENT['pro_account']['quality']

    if request.method == 'POST':
            
        if current_count < max_count:

            image = request.files['image'].stream.read()

            image_object = AIArtGenerator(
                prompt='',
                n=max_images,
                size=quality
            )

            response.update({"data": image_object.image_variation(image=image)})

app/templates/site/app/generate_art.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Generate Art {% endblock %}
<!-- title -->

<!-- body -->
{% block body %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<!-- content -->

<div id="app" class="container-fluid">
  <div class="container py-5">
    <div class="card text-center mb-3">
      <div class="card-header">How it works</div>
      <div class="card-body">
        <h5 class="card-title fw-bold">Text to AI generated art</h5>
        <p class="card-text">
          You to create an original image given a
          <span class="text-primary">text prompt</span>. Generated images can
          have a size of <span class="text-primary">256x256</span>,
          <span class="text-primary">512x512</span>, or
          <span class="text-primary">1024x1024</span> pixels. Smaller sizes are
          faster to generate. You can request 1-4 images at a time using the
          <span class="text-primary">number</span>
          parameter.
        </p>
        <p class="card-text">
          The more detailed the description, the better the result that you will
          get.
        </p>
        <button
          class="btn btn-outline-secondary container fluid"
          data-bs-toggle="modal"
          data-bs-target="#generateArtModal"
        >
          Generate Art
        </button>
      </div>
    </div>
    {% if generated_response %}
    <div class="card mb-3">
      <h1 class="card-title text-center mt-3">Recently generated images</h1>
      <div class="card-body d-flex justify-content-center alaign-items-center">
        {% for image in generated_response %}
        <div class="card mx-3 shadow">
          <img src="{{ image.url }}" alt="generated art" class="card-img-top" />
          <div
            class="card-body d-flex justify-content-center alaign-items-center"
          >
            <a
              href="{{ image.url }}"
              class="btn btn-sm btn-outline-success mx-1 container-fluid"
              target="_blank"
              download
            >
              View Image
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="card mb-3">
      <div class="card-body">
        <h1 class="card-title text-center mt-3">
          Generated images will appear here
        </h1>
      </div>
    </div>
    {% endif %}
    <div class="text-center card bg-light">
      <div class="card-body d-flex flex-column">
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Current generation count:
          <span class="fw-bold">{{ this_account.generation_count }}</span>
        </p>
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Max generation count: <span class="fw-bold"> {{ max_count }} </span>
        </p>
        <p class="card-text">
          What are generation counts?
          <a href="{{ url_for('site.pricing') }}">Learn more</a>.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- notifications -->
<div class="site-alerts">{% include 'notifications.html' %}</div>
<!-- notifications -->

<!-- content -->

<!-- modals -->
{% include 'site/app/modals.html' %}
<!-- modals -->

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- body -->

app/templates/site/app/image_variation.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Image Variation {% endblock %}
<!-- title -->

<!-- body -->
{% block body %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<!-- content -->

<div id="app" class="container-fluid">
  <div class="container py-5">
    <div class="card text-center mb-3">
      <div class="card-header">How it works</div>
      <div class="card-body">
        <h5 class="card-title fw-bold">Image to AI generated art</h5>
        <p class="card-text">generate a variation of a given image.</p>
        <p class="card-text">
          Similar to the image to art endpoint, the input image must be a square
          PNG image less than 4MB in size.
        </p>
        <button
          class="btn btn-outline-secondary container fluid"
          data-bs-toggle="modal"
          data-bs-target="#imageVariationModal"
        >
          Generate Art
        </button>
      </div>
    </div>
    {% if generated_response %}
    <div class="card mb-3">
      <h1 class="card-title text-center mt-3">Recently generated images</h1>
      <div class="card-body d-flex justify-content-center alaign-items-center">
        {% for image in generated_response %}
        <div class="card mx-3 shadow">
          <img src="{{ image.url }}" alt="generated art" class="card-img-top" />
          <div
            class="card-body d-flex justify-content-center alaign-items-center"
          >
            <a
              href="{{ image.url }}"
              class="btn btn-sm btn-outline-success mx-1 container-fluid"
              target="_blank"
              download
            >
              View Image
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="card mb-3">
      <div class="card-body">
        <h1 class="card-title text-center mt-3">
          Generated images will appear here
        </h1>
      </div>
    </div>
    {% endif %}
    <div class="text-center card bg-light">
      <div class="card-body d-flex flex-column">
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Current generation count:
          <span class="fw-bold">{{ this_account.generation_count }}</span>
        </p>
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Max generation count: <span class="fw-bold"> {{ max_count }} </span>
        </p>
        <p class="card-text">
          What are generation counts?
          <a href="{{ url_for('site.pricing') }}">Learn more</a>.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- notifications -->
<div class="site-alerts">{% include 'notifications.html' %}</div>
<!-- notifications -->

<!-- content -->

<!-- modals -->
{% include 'site/app/modals.html' %}
<!-- modals -->

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- body -->

app/templates/site/app/modals.html
<!-- generate art modal -->
<div
  class="modal fade"
  id="generateArtModal"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="generateArtModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="generateArtModalLabel">Generate Art</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form
          action="{{ url_for('site.generate_art') }}"
          method="post"
          id="generate-art-form"
        >
          <div class="mb-3">
            <label for="username" class="form-label"
              >Art style to be applied</label
            >
            <select
              class="form-select"
              name="style"
              aria-label="Art style for generated art"
            >
              <option selected class="text-primary">
                Select your desired art style
              </option>
              <option value="Renaissance">Renaissance</option>
              <option value="Baroque">Baroque</option>
              <option value="Rococo">Rococo</option>
              <option value="Neoclassicism">Neoclassicism</option>
              <option value="Romanticism">Romanticism</option>
              <option value="Realism">Realism</option>
              <option value="Impressionism">Impressionism</option>
              <option value="Expressionism">Expressionism</option>
              <option value="Cubism">Cubism</option>
              <option value="Surrealism">Surrealism</option>
              <option value="Ukiyo-e">Ukiyo-e</option>
              <option value="Line art">Line art</option>
              <option value="Pencil art">Pencil art</option>
              <option value="Digital art">Digital art</option>
              <option value="Custom">Custom</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="text-prompt" class="form-label">Text prompt</label>
            <textarea
              class="form-control"
              id="text-prompt"
              name="text_prompt"
              rows="7"
              placeholder="In detail describe the image you want to create"
            ></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-success container-fluid"
          onclick="generateArt()"
        >
          Submit
        </button>
      </div>
    </div>
  </div>
</div>
<!-- generate art modal -->

<!-- image to art modal -->
<div
  class="modal fade"
  id="imageToArtModal"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="imageToArtModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageToArtModalLabel">Generate Art</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form
          action="{{ url_for('site.photo_to_art') }}"
          enctype="multipart/form-data"
          method="post"
          id="photo-to-art-form"
        >
          <div class="mb-3">
            <label for="username" class="form-label"
              >Art style to be applied</label
            >
            <select
              class="form-select"
              name="style"
              aria-label="Art style for generated art"
            >
              <option selected class="text-primary">
                Select your desired art style
              </option>
              <option value="Renaissance">Renaissance</option>
              <option value="Baroque">Baroque</option>
              <option value="Rococo">Rococo</option>
              <option value="Neoclassicism">Neoclassicism</option>
              <option value="Romanticism">Romanticism</option>
              <option value="Realism">Realism</option>
              <option value="Impressionism">Impressionism</option>
              <option value="Expressionism">Expressionism</option>
              <option value="Cubism">Cubism</option>
              <option value="Surrealism">Surrealism</option>
              <option value="Ukiyo-e">Ukiyo-e</option>
              <option value="Line art">Line art</option>
              <option value="Pencil art">Pencil art</option>
              <option value="Digital art">Digital art</option>
              <option value="Custom">Custom</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="formFile" class="form-label"
              >Image to generate art from</label
            >
            <input
              class="form-control"
              name="image"
              type="file"
              id="formFile"
            />
          </div>
          <div class="mb-3">
            <label for="text-prompt" class="form-label">Text prompt</label>
            <textarea
              class="form-control"
              id="text-prompt"
              name="text_prompt"
              rows="7"
              placeholder="In detail describe the image you want to create"
            ></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-success container-fluid"
          onclick="photoToArt()"
        >
          Submit
        </button>
      </div>
    </div>
  </div>
</div>
<!-- image to art modal -->

<!-- image variation modal -->
<div
  class="modal fade"
  id="imageVariationModal"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="imageVariationModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="imageVariationModalLabel">Generate Art</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body">
        <form
          action="{{ url_for('site.image_variation') }}"
          enctype="multipart/form-data"
          method="post"
          id="image-variation-form"
        >
          <div class="mb-3">
            <label for="formFile" class="form-label"
              >Image to generate art from</label
            >
            <input
              class="form-control"
              name="image"
              type="file"
              id="formFile"
            />
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-success container-fluid"
          onclick="imageVariation()"
        >
          Submit
        </button>
      </div>
    </div>
  </div>
</div>
<!-- image variation modal -->

app/templates/site/app/photo_to_art.html
{% extends 'base.html' %}

<!-- title -->
{% block title %} Image To Art {% endblock %}
<!-- title -->

<!-- body -->
{% block body %}
<!-- navbar -->
{% include 'navbar.html' %}
<!-- navbar -->

<!-- content -->

<div id="app" class="container-fluid">
  <div class="container py-5">
    <div class="card text-center mb-3">
      <div class="card-header">How it works</div>
      <div class="card-body">
        <h5 class="card-title fw-bold">Image to AI generated art</h5>
        <p class="card-text">
          You can edit and extend an image by uploading a
          <span class="text-primary">mask</span>. The transparent areas of the
          mask indicate where the image should be edited, and the
          <span class="text-primary">prompt</span> should describe the full new
          image, not just the erased area.
        </p>
        <p class="card-text">
          The uploaded image and mask must both be square PNG images less than
          4MB in size, and also must have the same dimensions as each other. The
          non-transparent areas of the mask are not used when generating the
          output, so they don’t necessarily need to match the original image
          like the example above.
        </p>
        <button
          class="btn btn-outline-secondary container fluid"
          data-bs-toggle="modal"
          data-bs-target="#imageToArtModal"
        >
          Generate Art
        </button>
      </div>
    </div>
    {% if generated_response %}
    <div class="card mb-3">
      <h1 class="card-title text-center mt-3">Recently generated images</h1>
      <div class="card-body d-flex justify-content-center alaign-items-center">
        {% for image in generated_response %}
        <div class="card mx-3 shadow">
          <img src="{{ image.url }}" alt="generated art" class="card-img-top" />
          <div
            class="card-body d-flex justify-content-center alaign-items-center"
          >
            <a
              href="{{ image.url }}"
              class="btn btn-sm btn-outline-success mx-1 container-fluid"
              target="_blank"
              download
            >
              View Image
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="card mb-3">
      <div class="card-body">
        <h1 class="card-title text-center mt-3">
          Generated images will appear here
        </h1>
      </div>
    </div>
    {% endif %}
    <div class="text-center card bg-light">
      <div class="card-body d-flex flex-column">
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Current generation count:
          <span class="fw-bold">{{ this_account.generation_count }}</span>
        </p>
        <p class="card-text btn btn-sm btn-outline-dark disabled">
          Max generation count: <span class="fw-bold"> {{ max_count }} </span>
        </p>
        <p class="card-text">
          What are generation counts?
          <a href="{{ url_for('site.pricing') }}">Learn more</a>.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- notifications -->
<div class="site-alerts">{% include 'notifications.html' %}</div>
<!-- notifications -->

<!-- content -->

<!-- modals -->
{% include 'site/app/modals.html' %}
<!-- modals -->

<!-- footer -->
{% include 'footer.html' %}
<!-- footer -->
{% endblock %}
<!-- body -->